apiVersion: farmcontroller.toinfn.it/v1alpha1
resourceVersion: "v1alpha1"
kind: Farm
metadata:
  name: jupyter-svallero
  namespace: svallero
  #resourceVersion: 1
spec:
  # Add fields here
  labelKey: spark-role
  labelValue: executor
  minExecutors: 25
  maxExecutors: 0
  scaledownAfterNTriggers: 100
