apiVersion: farmcontroller.toinfn.it/v1alpha1
resourceVersion: "v1alpha1"
kind: Farm
#&labelKey: spark-role
#&labelValue: executor
metadata:
  name: jupyter-svallero
  namespace: svallero
  labels:
    #*labelKey: *labelValue
    spark-role: executor
  #resourceVersion: 1
spec:
  # Add fields here
  labelKey: spark-role
  labelValue: executor
  minExecutors: 25
  replicas: 30
